spring:
  application:
    name: techtest
  jackson:
    default-property-inclusion: NON_ABSENT
    mapper:
      accept_case_insensitive_enums: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: h2
  h2:
    console.enabled: true

logging:
  level:
    org:
      hibernate :
        SQL : TRACE
        type :
          descriptor :
            sql :
              BasicBinder : TRACE
